Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 693-571-156
127.0.0.1 - - [17/May/2025 23:06:29] "GET /transaction.html HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:06:29] "GET /assets/transaction.css HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:06:29] "GET /assets/sidebar.css HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:06:29] "GET /assets/sidebar.js HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:06:29] "GET /assets/transactions.js HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:06:29] "GET /assets/dashboard.css HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:06:29] "GET /sidebar.html HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:06:29] "GET /users HTTP/1.1" 200 -
127.0.0.1 - - [17/May/2025 23:06:29] "GET /profile?username=DharaSwapna HTTP/1.1" 200 -
Incoming /predict data: {'sender_id': 'DharaSwapna', 'recipient_id': 'Neha', 'amount': 1900, 'transaction_type': 'transfer', 'timestamp': '2025-05-17T17:36:37.674Z', 'device_id': '5d773e1eaa605e84b4d237b5338d7422', 'geo_lat': 17.53088, 'geo_lon': 78.4564224, 'ip_address': '49.204.104.215'}
127.0.0.1 - - [17/May/2025 23:06:37] "POST /predict HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\backend\app.py", line 245, in predict
    proba = model.predict_proba(X)[0][1]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"New Transaction
Search User 
Neha
Transaction Type 
Transfer
Amount 
1900
Description 
Pay
Something went wrong. Please try again."


////////////////////

* Restarting with stat
 * Debugger is active!
 * Debugger PIN: 693-571-156
127.0.0.1 - - [17/May/2025 23:11:21] "GET /transaction.html HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:11:21] "GET /assets/transaction.css HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:11:21] "GET /assets/sidebar.js HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:11:21] "GET /assets/sidebar.css HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:11:21] "GET /assets/transactions.js HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:11:21] "GET /assets/dashboard.css HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:11:21] "GET /sidebar.html HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 23:11:22] "GET /users HTTP/1.1" 200 -
127.0.0.1 - - [17/May/2025 23:11:22] "GET /profile?username=DharaSwapna HTTP/1.1" 200 -
Incoming /predict data: {'sender_id': 'DharaSwapna', 'recipient_id': 'Neha', 'amount': 1900, 'transaction_type': 'transfer', 'timestamp': '2025-05-17T17:41:31.120Z', 'device_id': '5d773e1eaa605e84b4d237b5338d7422', 'geo_lat': 17.53088, 'geo_lon': 78.4564224, 'ip_address': '49.204.104.215'}
127.0.0.1 - - [17/May/2025 23:11:31] "POST /predict HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Fraud_Detection_V-01\backend\app.py", line 245, in predict
    proba = pipeline.predict_proba(X)[0][1]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'pipeline' is not defined 
